// const Images = {
//     img_me: require('../assets/img_me.jpg'),
//     logo: require('../assets/logo-min.png'),
//     bg_profile: require('../assets/bg_profile-min.png'),
//     bg_login: require('../assets/bg_login-min.png'),
//     bg_touchID: require('../assets/bg_touchID-min.png'),
//     icon_bg_audio: require('../assets/icon_bg_audio-min.png'),
//     icon_bg_camera: require('../assets/icon_bg_camera-min.png'),
//     icon_bg_document: require('../assets/icon_bg_document-min.png'),
//     icon_bg_image: require('../assets/icon_bg_image-min.png'),
//     icon_bg_location: require('../assets/icon_bg_location-min.png'),
//     icon_bg_video: require('../assets/icon_bg_video-min.png'),
//     icon_username: require('../assets/icon_username-min.png'),
//     icon_password: require('../assets/icon_password-min.png'),
//     icon_finger_print: require('../assets/icon_finger_print-min.png'),
//     icon_drawer: require('../assets/icon_drawer-min.png'),
//     icon_search: require('../assets/icon_search-min.png'),
//     icon_tab_contacts: require('../assets/icon_tab_contacts-min.png'),
//     icon_tab_contacts_active: require('../assets/icon_tab_contacts_active-min.png'),
//     icon_tab_chats: require('../assets/icon_tab_chats-min.png'),
//     icon_tab_chats_active: require('../assets/icon_tab_chats_active-min.png'),
//     icon_tab_notifications: require('../assets/icon_tab_notifications-min.png'),
//     icon_tab_notifications_active: require('../assets/icon_tab_notifications_active-min.png'),
//     icon_tab_channels: require('../assets/icon_tab_channels-min.png'),
//     icon_tab_channels_active: require('../assets/icon_tab_channels_active-min.png'),
//     icon_channel: require('../assets/icon_channel-min.png'),
//     icon_new_group: require('../assets/icon_new_group-min.png'),
//     icon_delete: require('../assets/icon_delete-min.png'),
//     icon_pin: require('../assets/icon_pin-min.png'),
//     icon_pen: require('../assets/icon_pen-min.png'),
//     icon_user_plus: require('../assets/icon_user_plus-min.png'),
//     icon_emergency: require('../assets/icon_emergency-min.png'),
//     icon_comment_right: require('../assets/icon_comment_right-min.png'),
//     icon_comment_left: require('../assets/icon_comment_left-min.png'),
//     icon_phone: require('../assets/icon_phone-min.png'),
//     icon_camera: require('../assets/icon_camera-min.png'),
//     icon_verify: require('../assets/icon_verify-min.png'),
//     icon_book: require('../assets/icon_book-min.png'),
//     icon_bus: require('../assets/icon_bus-min.png'),
//     icon_mic: require('../assets/icon_mic-min.png'),
//     icon_sync: require('../assets/icon_sync-min.png')
// }

// export default Images
